name: Test DNSHE API

on:
  workflow_dispatch:

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v5


    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.x"


    - name: Install requests
      run: |
        pip install requests


    - name: Run DNS record test
      run: |
        python test.py
