name: Update DNSHE CF IP

on:
  schedule:
    - cron: "*/10 * * * *"   # 每10分钟执行一次
  workflow_dispatch:       # 支持手动执行

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      DNSHE_KEY: ${{ secrets.DNSHE_KEY }}
      DNSHE_SECRET: ${{ secrets.DNSHE_SECRET }}
      TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
      TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps chromium

      - name: Run updater
        env:
          DNSHE_KEY: ${{ secrets.DNSHE_KEY }}
          DNSHE_SECRET: ${{ secrets.DNSHE_SECRET }}
        run: python main.py
